### ISSUE TITLE
asm/code_8001F980.s:3150: Error: invalid operands `lw $a0,%lo(D_800DC4DC)$a0)'

### ISSUE THREAD

**Issue by Tatsh** [n64decomp/mk64#14]
Change from #11 breaks assembler.

```
mips64-elf-as -march=vr4300 -mabi=32 -I include -I build/us --defsym F3DEX_GBI=1 -o build/us/asm/code_8001F980.o asm/code_8001F980.s
asm/code_8001F980.s: Assembler messages:
asm/code_8001F980.s:3150: Error: invalid operands `lw $a0,%lo(D_800DC4DC)$a0)'
make: *** [Makefile:206: build/us/asm/code_8001F980.o] Error 1
```

https://github.com/n64decomp/mk64/blob/850e3b2fe9f31e2b65d0d24b0de415af3b8fd79c/asm/code_8001F980.s#L3150

Going back to what it was makes it build.

**Comment by Tatsh** [comment]
Did you mean to write `%lo(D_800DC4DC)($a0)` (missing `(`)?

**Comment by MegaMech** [comment]
Yes that was a spelling mistake. Thanks for letting us know.
