### ISSUE TITLE
Add script to fix windows line endings.

### ISSUE THREAD

**Issue by MegaMech** [n64decomp/mk64#185]
Tried a script from zeldaret. Didn't comprehend how it worked.

Windows line endings result in unknown character warnings.

**Comment by valandil** [comment]
I don't know what's the scope of the script, but if you want to preserve line endings across platforms, a `.gitattributes` file could be helpful: https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings
