### ISSUE TITLE
Add 100x player capability

### ISSUE THREAD

**Issue by space-mvc** [n64decomp/mk64#5]
Hi,

do you think it would be possible to allow for unlimited players or 100 players

this could be all on one screen or 4 screen split with random or selective player following with camera. Maybe make the 3x other screen follow the leaders of the race

this would be excellent with lan network player capability

**Comment by ProjectRevoTPP** [comment]
🤣🤣🤣🤣🤣

**Comment by MegaMech** [comment]
Hello,

You have posted on the incorrect repository. I believe you meant to ask this on sm64ex-coop. You may also find the Discord link on there and can ask your question in the suggestions channel.

https://github.com/djoslin0/sm64ex-coop

**Comment by MegaMech** [comment]
@space-mvc I recommend reading the readme for Mario Kart 64. This is beyond the scope of this project. Consider looking for the "Overkart" project as it is the current community for modding Mario Kart 64.

**Comment by MegaMech** [comment]
@space-mvc I recommend reading the readme for Mario Kart 64. This is beyond the scope of this project. Consider looking for the "Overkart" project as it is the current community for modding Mario Kart 64.
