### ISSUE TITLE
Assembler Formatting Warning other_textures.s 

### ISSUE THREAD

**Issue by Whoblue579** [n64decomp/mk64#91]
```
data/other_textures.s: Assembler messages:
data/other_textures.s:1423: Warning: end of file not at end of a line; newline inserted
```

**Comment by MegaMech** [comment]
This can be fixed by adding a new line to the end of the `other_textures.s` file. Feel free to open a PR to do that. Generally it's not necessary to open issues for warnings such as this. It automatically puts a newline in too.
